name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Setup Go 1.18rc1
      run: |
        go install golang.org/dl/go1.18rc1@latest
        go1.18rc1 download

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go1.18rc1 get -v -t -d ./...

    - name: Build
      run: go1.18rc1 build -v ./...

    - name: Test
      run: go1.18rc1 test -v -race -cover ./...
